// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

Future<LabReply> startLab({required String parent}) =>
    RustLib.instance.api.crateApiLabStartLab(parent: parent);

Future<LabReply> executeLab({
  required int session,
  required LabAction action,
  required int count,
}) => RustLib.instance.api.crateApiLabExecuteLab(
  session: session,
  action: action,
  count: count,
);

Future<LabReply> closeLab({required int session}) =>
    RustLib.instance.api.crateApiLabCloseLab(session: session);

/// Measures bridge copying/dispatch only, not encryption. Does not echo data.
Future<int> ping({required List<int> payload}) =>
    RustLib.instance.api.crateApiLabPing(payload: payload);

enum LabAction { exchange, exchangeBatch, update, addThird, removeThird }

class LabReply {
  final int session;
  final int epoch;
  final int members;
  final int delivered;
  final double queueMs;
  final double nativeMs;
  final double sendMs;
  final double receiveMs;
  final double receiveBeginMs;
  final double receiveGroupLoadMs;
  final double receiveWorkAndSqlMs;
  final double receiveCommitMs;
  final int receiveTransactions;

  const LabReply({
    required this.session,
    required this.epoch,
    required this.members,
    required this.delivered,
    required this.queueMs,
    required this.nativeMs,
    required this.sendMs,
    required this.receiveMs,
    required this.receiveBeginMs,
    required this.receiveGroupLoadMs,
    required this.receiveWorkAndSqlMs,
    required this.receiveCommitMs,
    required this.receiveTransactions,
  });

  @override
  int get hashCode =>
      session.hashCode ^
      epoch.hashCode ^
      members.hashCode ^
      delivered.hashCode ^
      queueMs.hashCode ^
      nativeMs.hashCode ^
      sendMs.hashCode ^
      receiveMs.hashCode ^
      receiveBeginMs.hashCode ^
      receiveGroupLoadMs.hashCode ^
      receiveWorkAndSqlMs.hashCode ^
      receiveCommitMs.hashCode ^
      receiveTransactions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LabReply &&
          runtimeType == other.runtimeType &&
          session == other.session &&
          epoch == other.epoch &&
          members == other.members &&
          delivered == other.delivered &&
          queueMs == other.queueMs &&
          nativeMs == other.nativeMs &&
          sendMs == other.sendMs &&
          receiveMs == other.receiveMs &&
          receiveBeginMs == other.receiveBeginMs &&
          receiveGroupLoadMs == other.receiveGroupLoadMs &&
          receiveWorkAndSqlMs == other.receiveWorkAndSqlMs &&
          receiveCommitMs == other.receiveCommitMs &&
          receiveTransactions == other.receiveTransactions;
}
